using BaseLib.Utils;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Cards;
using Painter.PainterCode.Canvas;

namespace Painter.PainterCode.Cards.Status;

// GrayGloom is a Status card generated by other cards (Sweeping Sadness, Blank Bane).
// It is NOT collectible and should not appear in card rewards.
public class GrayGloom() : PainterCard(1, CardType.Skill, CardRarity.Common, TargetType.Self)
{
    protected override IEnumerable<DynamicVar> CanonicalVars => [new IntVar("wounds", 2m)];

    protected override async Task OnPlay(PlayerChoiceContext ctx, CardPlay play)
    {
        var woundCount = DynamicVars["wounds"].IntValue;
        await CardPileCmd.AddToCombatAndPreview<Wound>(Owner.Creature, PileType.Hand, woundCount, false);

        CanvasManager.Current.PaintColor(PaintColor.Gray);
    }

    protected override void OnUpgrade()
    {
        DynamicVars["wounds"].UpgradeValueBy(1m);
    }
}
